### PR TITLE
Allow enter on clope select

### PR DESCRIPTION
**Pull request by matthieu-gendreau**
Two bad things:
1) I didn't manage to use bootstrap_form_tag to do a select multiple
2) The select multiple doesn't really fit aesthetically

### CODE REVIEW

**Comment by tdeo** [comment]
This a a nightmare for scrolling, and also not very aesthetic. Can't you just capture right arrow on the bootstrap dropdown ?

**Comment by matthieu-gendreau** [comment]
I think a dropdown is not really what we want, you cannot "select" anything on a dropdown ?

**Comment by tdeo** [comment]
`<%= f.select(:clope_id, Clope.order(quantite: :desc).all.collect { |c| [c.marque, c.id] }, { hide_label: true }, { class: 'mousetrap', multiple: 'true'}) %>` does what you want.

**Comment by tdeo** [comment]
But it's bad because people can select multiple options...

**Comment by matthieu-gendreau** [comment]
Closing this one :)

**Pull request closed without merging**
